name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        run: |
          # الدخول لمجلد بوبليك وبدء البناء
          cd public
          bubblewrap init --manifest=manifest.json --no-prompt
          bubblewrap build --no-prompt
          # أمر سحري: نقل أي ملف apk تم إنتاجه إلى المجلد الرئيسي ليسهل رفعه
          find . -name "*.apk" -exec cp {} .. \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AbuZahra-Final-App
          # الآن سيبحث في المجلد الرئيسي مباشرة عن الملف الذي نقلناه
          path: "*.apk" 
          if-no-files-found: error
          
